name: starter_template_workspace
description: Root workspace for the Monorepo
publish_to: "none"

environment:
  sdk: ^3.9.2

dependencies:
  flutter:
    sdk: flutter

dev_dependencies:
  melos: ^6.0.0
